### ISSUE TITLE
Tord's private todo list

### ISSUE THREAD

**Issue by SunyataZero** [dave-theunsub/clamtk-gnome#1]
* [ ] Translation functionality (using the gettext python module?)
* [ ]

**Comment by SunyataZero** [comment]
https://python-gtk-3-tutorial.readthedocs.io/en/latest/
https://git.gnome.org/browse/pygobject/tree/gi/overrides/Gtk.py
https://wiki.gnome.org/Projects/NautilusPython

**Comment by SunyataZero** [comment]
https://bitbucket.org/dave_theunsub/build_files/src/3ec83b7948f68430ae5c709085c6487fc13c7c10/debian/clamtk-gnome/?at=master

**Comment by SunyataZero** [comment]
https://launchpad.net/~launchpad-translators

**Comment by SunyataZero** [comment]
My contact info:
* https://launchpad.net/~tord-dellsen
* _

**Comment by SunyataZero** [comment]
# SO question

sunyata@sunyata-Aspire-ES1-131:/usr/local/lib/python3.5/dist-packages$ sudo -H pip3 install PyGObject
Collecting PyGObject
  Using cached pygobject-2.28.3.tar.bz2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jz7_9lg4/PyGObject/setup.py", line 272
        raise SystemExit, 'ERROR: Nothing to do, gio could not be found and is essential.'
                        ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jz7_9lg4/PyGObject/
sunyata@sunyata-Aspire-ES1-131:/usr/local/lib/python3.5/dist-packages$



Ubuntu 16.04.1 LTS
64 bit

Python 3

python-dev is installed




# My notes

install GTK+3

gi


it works when running, so maybe looking at the build files??

**Comment by SunyataZero** [comment]
Problem: "unresolved reference" for some imports

Solution: File -> Invalidate Caches / Restart

**Comment by SunyataZero** [comment]
['',
'/usr/lib/python35.zip',
'/usr/lib/python3.5',
'/usr/lib/python3.5/plat-x86_64-linux-gnu',
'/usr/lib/python3.5/lib-dynload',
'/usr/local/lib/python3.5/dist-packages',
'/usr/lib/python3/dist-packages'
]


sudo apt-get install python-nautilus

This is probably a beginner's qustion but: If the package is installed
-> look at the build files

**Comment by SunyataZero** [comment]
The python script for our plugin is not stored in ~/.local/share/nautilus-python/extensions (like in this example: https://projects-old.gnome.org/nautilus-python/documentation/html/nautilus-python-overview-example.html), where is it stored instead?

**Comment by SunyataZero** [comment]
Warning:

`sys:1: PyGIWarning: Nautilus was imported without specifying a version first. Use gi.require_version('Nautilus', '3.0') before import to ensure that the right version gets loaded.`

This can be ignored because it is seen even when our code is not running:

```
sunyata@sunyata-Aspire-ES1-131:/usr/share/nautilus-python/extensions$ nautilus

(nautilus:4382): Gtk-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

sys:1: PyGIWarning: Nautilus was imported without specifying a version first. Use gi.require_version('Nautilus', '3.0') before import to ensure that the right version gets loaded.

Initializing nautilus-dropbox 2015.10.28

** (nautilus:4382): CRITICAL **: nautilus_menu_provider_get_background_items: assertion 'NAUTILUS_IS_MENU_PROVIDER (provider)' failed
```

**Comment by SunyataZero** [comment]
Inspiration: **https://github.com/dropbox/nautilus-dropbox**

**Comment by SunyataZero** [comment]
Can't see tooltips in nautilus

**Comment by SunyataZero** [comment]
For the clamtk project:
https://github.com/dave-theunsub/clamtk/issues/36

What about giving the user a warning and confirm button before removing all? Something like this:
> You are about to remove more than one virus at the same time. Please consider carefully before proceeding since _______________

**Comment by SunyataZero** [comment]
### Info
nautilus-python extensions can be stored here ```~/.local/share/nautilus-python/extensions``` or here ```/usr/share/nautilus-python/extensions/clamtk.py```

**Comment by SunyataZero** [comment]
### clamtk-gnome without running GNOME?

I am using LXDE and i can still run the nautilus plugin, but it's a little tricky, i may need to install python-gobject and perhaps another .deb package as well. NOTE: This is not certain though because

I managed to *run* clamtk-gnome without having installed the python-gobject .deb package on my Lubuntu distro with LXDE

**Comment by SunyataZero** [comment]
Translation tutorial:

http://inventwithpython.com/blog/2014/12/20/translate-your-python-3-program-with-the-gettext-module/

***For Python 2:***
> To make sure that when a string is translated whith the good characters, I format my string like this:
> print(_(u"My_string"))
> To encode it in utf-8 (to have accent in some languages like french or spanish).

**Comment by SunyataZero** [comment]
Debian packages: https://www.debian.org/doc/manuals/maint-guide/dreq.en.html

**Comment by SunyataZero** [comment]
sunyata@sunyata-Aspire-ES1-131:~$ locate clamtk.py
/home/sunyata/PycharmProjects/clamtk-gnome/clamtk.py
/home/sunyata/PycharmProjects/clamtk-gnome/clamtk.py.bak
/usr/share/nautilus-python/extensions/clamtk.py
sunyata@sunyata-Aspire-ES1-131:~$ 

sunyata@sunyata-Aspire-ES1-131:/usr/share/locale/sv/LC_MESSAGES$ ll clamtk*
-rw-r--r-- 1 root root 12942 okt 24  2015 clamtk.mo
sunyata@sunyata-Aspire-ES1-131:/usr/share/locale/sv/LC_MESSAGES$

**Comment by SunyataZero** [comment]
https://wiki.debian.org/Packaging
https://www.debian.org/doc/manuals/maint-guide/
https://wiki.debian.org/HowToPackageForDebian
https://www.debian.org/doc/manuals/packaging-tutorial/packaging-tutorial.en.pdf

**Comment by SunyataZero** [comment]
https://specifications.freedesktop.org/desktop-entry-spec/latest/

**Comment by SunyataZero** [comment]
### Doc updates

#### To restart
`killall nautilus`

**Comment by SunyataZero** [comment]
* [ ] get_file_items and get_background_items: Comment these to make it clear that they are called by Nautilus, cmp with this: http://bazaar.launchpad.net/~costales/folder-color/trunk/view/head:/nautilus-extension/folder-color.py

**Comment by SunyataZero** [comment]
clamtk bug: command line clamtk only accepts a full path for the directories, ex:
`sunyata@sunyata-Aspire-ES1-131:~/PycharmProjects/clamtk-gnome$ clamtk /home/sunyata/Pictures/`

**Comment by SunyataZero** [comment]
https://github.com/GNOME/nautilus/blob/master/src/nautilus-vfs-file.h
