### ISSUE TITLE
Doesn't support Nautilus 43

### ISSUE THREAD

**Issue by feschukov** [dave-theunsub/clamtk-gnome#17]
Nautilus version
```
$ nautilus --version
GNOME nautilus 43.0
```

When run nautilus:
```
$ nautilus
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/clamtk-gnome.py", line 29, in <module>
    gi.require_version("Nautilus", "3.0")
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 117, in require_version
    raise ValueError('Namespace %s is already loaded with version %s' %
ValueError: Namespace Nautilus is already loaded with version 4.0
```

After edit `/usr/share/nautilus-python/extensions/clamtk-gnome.py` 
```
gi.require_version("Nautilus", "4.0")
```
i get this error:
```
$ nautilus
Initializing clamtk-gnome

** (org.gnome.Nautilus:44385): CRITICAL **: 15:07:29.835: nautilus_column_provider_get_columns: assertion 'iface->get_columns != NULL' failed
TypeError: OpenTerminalExtension.get_file_items() missing 1 required positional argument: 'files'
TypeError: OpenTerminalExtension.get_background_items() missing 1 required positional argument: 'file'
TypeError: OpenTerminalExtension.get_file_items() missing 1 required positional argument: 'files'
TypeError: OpenTerminalExtension.get_background_items() missing 1 required positional argument: 'file'
TypeError: OpenTerminalExtension.get_file_items() missing 1 required positional argument: 'files'
TypeError: OpenTerminalExtension.get_background_items() missing 1 required positional argument: 'file'
TypeError: OpenTerminalExtension.get_file_items() missing 1 required positional argument: 'files'
TypeError: OpenTerminalExtension.get_background_items() missing 1 required positional argument: 'file'
```

**Comment by feschukov** [comment]
Look at the PR https://github.com/dave-theunsub/clamtk-gnome/pull/18 for this issue, please

**Comment by dave-theunsub** [comment]
Hi @feschukov ,

Thank you for letting me know.  I'll take a look this weekend.

In the meantime, what distro are you using?  Did you test on any other ones?

respectfully,
Dave M

**Comment by feschukov** [comment]
> In the meantime, what distro are you using?

Arch Linux latest, python-nautilus 4.0. 

> Did you test on any other ones?

No.

**Comment by dave-theunsub** [comment]
Hi @feschukov ,

Thanks for the reply.  I will test it on Ubuntu, Fedora, and Alma or Rocky.

respectfully,
Dave M

**Comment by dave-theunsub** [comment]
Hi @feschukov ,

Seems to build okay on Fedora. Waiting on Ubuntu to upgrade and I'll try it there.  I don't think it'll work on Alma or Rocky - they probably don't have nautilus-python 4 yet.

The code has been pushed to the repository.

respectfully,  
Dave M

**Comment by starsforeveryone** [comment]
I can confirm that clamtk-gnome doesn't work on the latest GNOME 43 (Arch / Endeavour OS).

There simply is no entry in the right-click menu, so I'm guessing the plugin isn't loaded properly.

**Comment by dave-theunsub** [comment]
Hi @starsforeveryone ,

I had 6.15 in draft release for a while for testing but have officially released it. This should fix that issue.  Let me know if it doesn't.

respectfully,
Dave M
